// Generated by gencpp from file class_exercises/DistanceToResponse.msg
// DO NOT EDIT!


#ifndef CLASS_EXERCISES_MESSAGE_DISTANCETORESPONSE_H
#define CLASS_EXERCISES_MESSAGE_DISTANCETORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace class_exercises
{
template <class ContainerAllocator>
struct DistanceToResponse_
{
  typedef DistanceToResponse_<ContainerAllocator> Type;

  DistanceToResponse_()
    : distance(0.0)  {
    }
  DistanceToResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::class_exercises::DistanceToResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::class_exercises::DistanceToResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceToResponse_

typedef ::class_exercises::DistanceToResponse_<std::allocator<void> > DistanceToResponse;

typedef boost::shared_ptr< ::class_exercises::DistanceToResponse > DistanceToResponsePtr;
typedef boost::shared_ptr< ::class_exercises::DistanceToResponse const> DistanceToResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::class_exercises::DistanceToResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::class_exercises::DistanceToResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace class_exercises

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'class_exercises': ['/home/keaton/Mapping_Wall_Follow/src/class_exercises/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::class_exercises::DistanceToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::class_exercises::DistanceToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_exercises::DistanceToResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::class_exercises::DistanceToResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "class_exercises/DistanceToResponse";
  }

  static const char* value(const ::class_exercises::DistanceToResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
";
  }

  static const char* value(const ::class_exercises::DistanceToResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceToResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::class_exercises::DistanceToResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::class_exercises::DistanceToResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLASS_EXERCISES_MESSAGE_DISTANCETORESPONSE_H
