// Generated by gencpp from file class_exercises/DistanceTo.msg
// DO NOT EDIT!


#ifndef CLASS_EXERCISES_MESSAGE_DISTANCETO_H
#define CLASS_EXERCISES_MESSAGE_DISTANCETO_H

#include <ros/service_traits.h>


#include <class_exercises/DistanceToRequest.h>
#include <class_exercises/DistanceToResponse.h>


namespace class_exercises
{

struct DistanceTo
{

typedef DistanceToRequest Request;
typedef DistanceToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistanceTo
} // namespace class_exercises


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::class_exercises::DistanceTo > {
  static const char* value()
  {
    return "ac27abe74468bad30bf32e9b9ef409fa";
  }

  static const char* value(const ::class_exercises::DistanceTo&) { return value(); }
};

template<>
struct DataType< ::class_exercises::DistanceTo > {
  static const char* value()
  {
    return "class_exercises/DistanceTo";
  }

  static const char* value(const ::class_exercises::DistanceTo&) { return value(); }
};


// service_traits::MD5Sum< ::class_exercises::DistanceToRequest> should match 
// service_traits::MD5Sum< ::class_exercises::DistanceTo > 
template<>
struct MD5Sum< ::class_exercises::DistanceToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::class_exercises::DistanceTo >::value();
  }
  static const char* value(const ::class_exercises::DistanceToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::class_exercises::DistanceToRequest> should match 
// service_traits::DataType< ::class_exercises::DistanceTo > 
template<>
struct DataType< ::class_exercises::DistanceToRequest>
{
  static const char* value()
  {
    return DataType< ::class_exercises::DistanceTo >::value();
  }
  static const char* value(const ::class_exercises::DistanceToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::class_exercises::DistanceToResponse> should match 
// service_traits::MD5Sum< ::class_exercises::DistanceTo > 
template<>
struct MD5Sum< ::class_exercises::DistanceToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::class_exercises::DistanceTo >::value();
  }
  static const char* value(const ::class_exercises::DistanceToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::class_exercises::DistanceToResponse> should match 
// service_traits::DataType< ::class_exercises::DistanceTo > 
template<>
struct DataType< ::class_exercises::DistanceToResponse>
{
  static const char* value()
  {
    return DataType< ::class_exercises::DistanceTo >::value();
  }
  static const char* value(const ::class_exercises::DistanceToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLASS_EXERCISES_MESSAGE_DISTANCETO_H
