// Generated by gencpp from file irobotcreate2/Battery.msg
// DO NOT EDIT!


#ifndef IROBOTCREATE2_MESSAGE_BATTERY_H
#define IROBOTCREATE2_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace irobotcreate2
{
template <class ContainerAllocator>
struct Battery_
{
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
    : header()
    , power_cord(false)
    , dock(false)
    , level(0.0)
    , time_remaining(0)  {
    }
  Battery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , power_cord(false)
    , dock(false)
    , level(0.0)
    , time_remaining(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _power_cord_type;
  _power_cord_type power_cord;

   typedef uint8_t _dock_type;
  _dock_type dock;

   typedef float _level_type;
  _level_type level;

   typedef uint32_t _time_remaining_type;
  _time_remaining_type time_remaining;




  typedef boost::shared_ptr< ::irobotcreate2::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobotcreate2::Battery_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_

typedef ::irobotcreate2::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::irobotcreate2::Battery > BatteryPtr;
typedef boost::shared_ptr< ::irobotcreate2::Battery const> BatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobotcreate2::Battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobotcreate2::Battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobotcreate2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'irobotcreate2': ['/home/keaton/Mapping_Wall_Follow/src/driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Battery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Battery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobotcreate2::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fea569ed505a7f18307badadb1c26b0c";
  }

  static const char* value(const ::irobotcreate2::Battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfea569ed505a7f18ULL;
  static const uint64_t static_value2 = 0x307badadb1c26b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::irobotcreate2::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobotcreate2/Battery";
  }

  static const char* value(const ::irobotcreate2::Battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobotcreate2::Battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool power_cord\n\
bool dock\n\
float32 level			# in %\n\
uint32 time_remaining		# in minutes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::irobotcreate2::Battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobotcreate2::Battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.power_cord);
      stream.next(m.dock);
      stream.next(m.level);
      stream.next(m.time_remaining);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobotcreate2::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobotcreate2::Battery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "power_cord: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.power_cord);
    s << indent << "dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dock);
    s << indent << "level: ";
    Printer<float>::stream(s, indent + "  ", v.level);
    s << indent << "time_remaining: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_remaining);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOTCREATE2_MESSAGE_BATTERY_H
