// Generated by gencpp from file irobotcreate2/Buttons.msg
// DO NOT EDIT!


#ifndef IROBOTCREATE2_MESSAGE_BUTTONS_H
#define IROBOTCREATE2_MESSAGE_BUTTONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace irobotcreate2
{
template <class ContainerAllocator>
struct Buttons_
{
  typedef Buttons_<ContainerAllocator> Type;

  Buttons_()
    : header()
    , clean(false)
    , spot(false)
    , dock(false)
    , day(false)
    , hour(false)
    , minute(false)
    , schedule(false)
    , clock(false)  {
    }
  Buttons_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , clean(false)
    , spot(false)
    , dock(false)
    , day(false)
    , hour(false)
    , minute(false)
    , schedule(false)
    , clock(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _clean_type;
  _clean_type clean;

   typedef uint8_t _spot_type;
  _spot_type spot;

   typedef uint8_t _dock_type;
  _dock_type dock;

   typedef uint8_t _day_type;
  _day_type day;

   typedef uint8_t _hour_type;
  _hour_type hour;

   typedef uint8_t _minute_type;
  _minute_type minute;

   typedef uint8_t _schedule_type;
  _schedule_type schedule;

   typedef uint8_t _clock_type;
  _clock_type clock;




  typedef boost::shared_ptr< ::irobotcreate2::Buttons_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobotcreate2::Buttons_<ContainerAllocator> const> ConstPtr;

}; // struct Buttons_

typedef ::irobotcreate2::Buttons_<std::allocator<void> > Buttons;

typedef boost::shared_ptr< ::irobotcreate2::Buttons > ButtonsPtr;
typedef boost::shared_ptr< ::irobotcreate2::Buttons const> ButtonsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobotcreate2::Buttons_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobotcreate2::Buttons_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobotcreate2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'irobotcreate2': ['/home/keaton/Mapping_Wall_Follow/src/driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Buttons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Buttons_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Buttons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Buttons_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Buttons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Buttons_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobotcreate2::Buttons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c6635fea08c0a11307b4518b1f7fd79";
  }

  static const char* value(const ::irobotcreate2::Buttons_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c6635fea08c0a11ULL;
  static const uint64_t static_value2 = 0x307b4518b1f7fd79ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobotcreate2::Buttons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobotcreate2/Buttons";
  }

  static const char* value(const ::irobotcreate2::Buttons_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobotcreate2::Buttons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool clean\n\
bool spot\n\
bool dock\n\
bool day\n\
bool hour\n\
bool minute\n\
bool schedule\n\
bool clock\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::irobotcreate2::Buttons_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobotcreate2::Buttons_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.clean);
      stream.next(m.spot);
      stream.next(m.dock);
      stream.next(m.day);
      stream.next(m.hour);
      stream.next(m.minute);
      stream.next(m.schedule);
      stream.next(m.clock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Buttons_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobotcreate2::Buttons_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobotcreate2::Buttons_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "clean: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clean);
    s << indent << "spot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.spot);
    s << indent << "dock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dock);
    s << indent << "day: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.day);
    s << indent << "hour: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hour);
    s << indent << "minute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.minute);
    s << indent << "schedule: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.schedule);
    s << indent << "clock: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOTCREATE2_MESSAGE_BUTTONS_H
