// Generated by gencpp from file irobotcreate2/Diagnostic.msg
// DO NOT EDIT!


#ifndef IROBOTCREATE2_MESSAGE_DIAGNOSTIC_H
#define IROBOTCREATE2_MESSAGE_DIAGNOSTIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace irobotcreate2
{
template <class ContainerAllocator>
struct Diagnostic_
{
  typedef Diagnostic_<ContainerAllocator> Type;

  Diagnostic_()
    : header()
    , left_motor_current(0)
    , right_motor_current(0)
    , main_brush_current(0)
    , side_brush_current(0)
    , left_motor_overcurrent(false)
    , right_motor_overcurrent(false)
    , main_brush_overcurrent(false)
    , side_brush_overcurrent(false)
    , battery_current(0)
    , battery_voltage(0)
    , battery_temperature(0)  {
    }
  Diagnostic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_motor_current(0)
    , right_motor_current(0)
    , main_brush_current(0)
    , side_brush_current(0)
    , left_motor_overcurrent(false)
    , right_motor_overcurrent(false)
    , main_brush_overcurrent(false)
    , side_brush_overcurrent(false)
    , battery_current(0)
    , battery_voltage(0)
    , battery_temperature(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _left_motor_current_type;
  _left_motor_current_type left_motor_current;

   typedef int16_t _right_motor_current_type;
  _right_motor_current_type right_motor_current;

   typedef int16_t _main_brush_current_type;
  _main_brush_current_type main_brush_current;

   typedef int16_t _side_brush_current_type;
  _side_brush_current_type side_brush_current;

   typedef uint8_t _left_motor_overcurrent_type;
  _left_motor_overcurrent_type left_motor_overcurrent;

   typedef uint8_t _right_motor_overcurrent_type;
  _right_motor_overcurrent_type right_motor_overcurrent;

   typedef uint8_t _main_brush_overcurrent_type;
  _main_brush_overcurrent_type main_brush_overcurrent;

   typedef uint8_t _side_brush_overcurrent_type;
  _side_brush_overcurrent_type side_brush_overcurrent;

   typedef int16_t _battery_current_type;
  _battery_current_type battery_current;

   typedef int16_t _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef int8_t _battery_temperature_type;
  _battery_temperature_type battery_temperature;




  typedef boost::shared_ptr< ::irobotcreate2::Diagnostic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobotcreate2::Diagnostic_<ContainerAllocator> const> ConstPtr;

}; // struct Diagnostic_

typedef ::irobotcreate2::Diagnostic_<std::allocator<void> > Diagnostic;

typedef boost::shared_ptr< ::irobotcreate2::Diagnostic > DiagnosticPtr;
typedef boost::shared_ptr< ::irobotcreate2::Diagnostic const> DiagnosticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::irobotcreate2::Diagnostic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::irobotcreate2::Diagnostic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace irobotcreate2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'irobotcreate2': ['/home/keaton/Mapping_Wall_Follow/src/driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::irobotcreate2::Diagnostic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::irobotcreate2::Diagnostic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::irobotcreate2::Diagnostic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5ab1a026621d8d87d7316b146c2ca2a";
  }

  static const char* value(const ::irobotcreate2::Diagnostic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5ab1a026621d8d8ULL;
  static const uint64_t static_value2 = 0x7d7316b146c2ca2aULL;
};

template<class ContainerAllocator>
struct DataType< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "irobotcreate2/Diagnostic";
  }

  static const char* value(const ::irobotcreate2::Diagnostic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 left_motor_current\n\
int16 right_motor_current\n\
int16 main_brush_current\n\
int16 side_brush_current\n\
bool left_motor_overcurrent\n\
bool right_motor_overcurrent\n\
bool main_brush_overcurrent\n\
bool side_brush_overcurrent\n\
int16 battery_current\n\
int16 battery_voltage\n\
int8 battery_temperature\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::irobotcreate2::Diagnostic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_motor_current);
      stream.next(m.right_motor_current);
      stream.next(m.main_brush_current);
      stream.next(m.side_brush_current);
      stream.next(m.left_motor_overcurrent);
      stream.next(m.right_motor_overcurrent);
      stream.next(m.main_brush_overcurrent);
      stream.next(m.side_brush_overcurrent);
      stream.next(m.battery_current);
      stream.next(m.battery_voltage);
      stream.next(m.battery_temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Diagnostic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::irobotcreate2::Diagnostic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::irobotcreate2::Diagnostic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_motor_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_motor_current);
    s << indent << "right_motor_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_motor_current);
    s << indent << "main_brush_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.main_brush_current);
    s << indent << "side_brush_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.side_brush_current);
    s << indent << "left_motor_overcurrent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_motor_overcurrent);
    s << indent << "right_motor_overcurrent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_motor_overcurrent);
    s << indent << "main_brush_overcurrent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.main_brush_overcurrent);
    s << indent << "side_brush_overcurrent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side_brush_overcurrent);
    s << indent << "battery_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.battery_current);
    s << indent << "battery_voltage: ";
    Printer<int16_t>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "battery_temperature: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery_temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IROBOTCREATE2_MESSAGE_DIAGNOSTIC_H
