(cl:in-package irobotcreate2-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEFT_MOTOR_CURRENT-VAL
          LEFT_MOTOR_CURRENT
          RIGHT_MOTOR_CURRENT-VAL
          RIGHT_MOTOR_CURRENT
          MAIN_BRUSH_CURRENT-VAL
          MAIN_BRUSH_CURRENT
          SIDE_BRUSH_CURRENT-VAL
          SIDE_BRUSH_CURRENT
          LEFT_MOTOR_OVERCURRENT-VAL
          LEFT_MOTOR_OVERCURRENT
          RIGHT_MOTOR_OVERCURRENT-VAL
          RIGHT_MOTOR_OVERCURRENT
          MAIN_BRUSH_OVERCURRENT-VAL
          MAIN_BRUSH_OVERCURRENT
          SIDE_BRUSH_OVERCURRENT-VAL
          SIDE_BRUSH_OVERCURRENT
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          BATTERY_TEMPERATURE-VAL
          BATTERY_TEMPERATURE
))